### ISSUE TITLE
Why is ninja called with -j 200?

### ISSUE THREAD

**Issue by robinchrist** [electron/build-tools#305]
Why is ninja called with the `-j 200` option?

(`Running "ninja -j 200 electron" in /data/dev/Coda/electron/src/out/Testing`)

From my experience, ninja is pretty good at figuring out how many jobs to use (afaik, the number of threads available is used which works very well)

**Comment by MarshallOfSound** [comment]
@robinchrist as you commented `ninja` defaults to the number of threads available on your machine because it has to run actual compile jobs, `build-tools` utilizes Electrons GOMA system which is a distributed compiler / caching service.  The number of actual compile jobs that run on your machine are capped to NumberOfThreads by the GOMA control process but ninja sends 200 requests at a time so that when you get cache hits the builds are dramatically faster.

Refs: https://github.com/electron/electron/blob/main/docs/development/goma.md
