### ISSUE TITLE
How to use the custom electron build after being built successfully.

### ISSUE THREAD

**Issue by hnguyen48206** [electron/build-tools#309]
Hi everyone, I have succesfully built electron on Windows using this build-tools with a custom electron src code. Now I have a Release folder which weighs more than 10GB but do not really know how I can start using it for building applications since the standard way to use electron is installing it through npm globally. I'm pretty new to nodejs and electron in general so any help would be much appriciated. 

Thank you.

**Comment by hnguyen48206** [comment]
Following the suggestions that I could find, puting the code into resoucres/app folder of the built will allow you to run your application using electron.exe file. However, I still do not know how to package my app to a single platform installable file *exe on windows for example.

**Comment by chevonc** [comment]
take a look at https://www.electron.build/ @hnguyen48206

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
