### ISSUE TITLE
How to switch from testing to release?

### ISSUE THREAD

**Issue by stefansundin** [electron/build-tools#446]
Hello.

I initialized my electron directory using the command suggested in the README:

```
e init --root=~/electron --bootstrap testing
```

Can I switch this directory to be a release build instead of testing? I would prefer to not have to do the whole download process again if it can be avoided.

I think the README should suggest a release build because I think that's what most people want. I think most of just want to apply some chromium patch that we found elsewhere. We don't even know how we would get value of a test build so I think there's little sense in suggesting it to newbies.

Thanks!

**Comment by codebytere** [comment]
@stefansundin this tool was built by and for people who work on and want to contribute to Electron in a more intensive capacity. We of course also want it to help lower the barrier to contribution and usage for people looking to contribute more specific or infrequent changes, but that use case is not the overriding one here. The default will continue to be testing, since it includes greater symbolication and enables debug checks within Electron and Chromium, which are important to effective local debugging and development.

To your second question, yes you can. There is a sample testing build included in the `example_configs` directory. Copy it into the `configs` directory, and then run:

```
$ e use release
$ e sync 
$ e build
```
