### ISSUE TITLE
`e init` should let you specify which electron version to clone

### ISSUE THREAD

**Issue by stefansundin** [electron/build-tools#447]
Hello.

I think it would be great if `e init` had a way to specify which electron version/tag/branch to clone. This would simplify setup and save time. Something like `--version v22.0.0` would clone the tag `v22.0.0`, or `--version 22-x-y` would clone the `22-x-y` branch.

I looked at the code to see if I could implement this myself but I don't understand what the evm config is passed to. There's lots of talk of "EVM" but nowhere does it explain what it is or how it functions. I can only guess that it is short for "Electron Version Manager" but that's probably wrong.

**Comment by ckerr** [comment]
I can't find a link to it now so maybe this has changed, but IIRC the upstream Chroimum workflow was explicitly "if you want to work on branch `foo`, what you do is `gclient sync` to pull origin/main and then `git checkout foo` + sync again. So that's what build-tools is doing, too.

`e` and `evm` are the same thing; it got shortened to `e` because that's clearly 3x more efficient :smile_cat: 

The origin of the name `evm` was because it was taking inspiration from the `nvm` scripts that let you choose between arbitrary Node installations. In this case, it was that you might have different local builds for electron 22, 23, etc and want a way to easily switch between them with `e use`.

**Comment by codebytere** [comment]
I'm in agreement with @ckerr  above. it's fairly trivial to check out/clone another version, but the default should, imo, always be `main` by convention
