### ISSUE TITLE
How do I package a self-compiled electron

### ISSUE THREAD

**Issue by 1339240789** [electron/build-tools#481]
I modified part of the code of electron and rebuilt a new electron through build-tools. May I ask how to package the electron compiled by myself using electron-Builder? The electron-Builder will only pack the electron compiled from the download website. How do I replace it?

**Comment by 1339240789** [comment]
@codebytere can  you help me?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
