### ISSUE TITLE
how can i build a ia32 electron

### ISSUE THREAD

**Issue by 1339240789** [electron/build-tools#483]
How should I configure the build for the specified platform and architecture?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
