### ISSUE TITLE
Adjust ninja parallism based on Goma cache status

### ISSUE THREAD

**Issue by samuelmaddock** [electron/build-tools#92]
By default, builds run using `ninja -j 200`. I assume this works well when using the [custom Electron Goma backend](https://github.com/electron/electron/blob/master/docs/development/goma.md). However, when building locally this parallelism likely doesn't help speedup builds when it greatly exceeds the number of local CPU cores.

I'd propose looking into checking whether the local user will be running the full build locally or utilizing a remote Goma backend. If running locally, the number of parallel build commands shouldn't far exceed the number of CPU cores.

For now, I'm adjusting the number of parallel commands by running `e build -j [number-of-cores + 2]`.

**Comment by MarshallOfSound** [comment]
The issue here is quite specific to Windows.  Our goma has a `cache-only` backend which unauthenticated users can reach.

On macOS and Linux you get basically guaranteed cache hits as we use sysroots / preset versions of Xcode / SDKs.

On Windows we rely on your global Windows SDK installation which could be _any_ version really.

This issue is multi parts

* We should look into using a fixed / set version of the Windows SDK to get maximum cache-hit
* If the goma build cache hit rate is stupidly low maybe lower the `-j` value
* Investigate if `goma` will actually try to build 200 things locally as I think it actually has an internal queue to prevent flooding your local machine

**Comment by MarshallOfSound** [comment]
> We should look into using a fixed / set version of the Windows SDK to get maximum cache-hit

This would be the best outcome here

**Comment by MarshallOfSound** [comment]
Closing as #92 appears to resolve this nicely
